### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [GameTechDev/GTS-GamesTaskScheduler#1]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") in [the function “Node::setWorkload”](https://github.com/GameTechDev/GTS-GamesTaskScheduler/blob/be899783666a68c00f54db83590db5276d268649/source/gts/include/gts/macro_scheduler/Node.h#L57 "Update candidate").

**Comment by bretalfieri** [comment]
Thanks. I'll fix this in the next drop.

**Comment by bretalfieri** [comment]
Fixed :)

**Comment by elfring** [comment]
It is interesting how [this software was adjusted](https://github.com/GameTechDev/GTS-GamesTaskScheduler/commit/04cb3929bbce6f12d13598088b926c3dc4c73910#diff-930665696c0bef8f7a059ec94676c094R108 "Some changes").

**Comment by bretalfieri** [comment]
Yes. The macro scheduler in a work in progress. This change was a move to more closely match the  interfaces of Workload to that of Task in the micro scheduler. The next, and likely final major change, will be the addition of a profile guided static scheduler. I hope to get that pushed in the next few weeks.
