### ISSUE TITLE
GTS vs TBB Flow graph

### ISSUE THREAD

**Issue by charlesarcher** [GameTechDev/GTS-GamesTaskScheduler#7]
Can someone explain what the difference is between GTS and TBB flow graph?
When would a developer choose this vs TBB?

Thanks!

**Comment by bretalfieri** [comment]
Commonalities:
- Both create a persistent DAG of Nodes.

Differences:
TBB:
- Provides data flow with their different Node flavors.
- TBB is a supported piece of commercial software.

GTS:
- GTS enables multi-domain scheduling for homogeneous and heterogeneous environment. In GTS the DAG is scheduled through the MacroScheduler. A MacroScheduler consumes ComputeResources and coordinates how Nodes are assigned to each ComputeResource. A ComputeResource is a scheduling domain. One can create domains for thread priority, core partitioning (Big/Little), CPU/GPU, etc. The goal was to allow the developer to carve up the system resources to best fit their application, and to allow custom implementations of what a MacroSchedulers, ComputeResources, and their supporting interfaces are.
